services:
  api:
    build: .
    env_file: .env.prod
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery_domain_worker:
    build: .
    env_file: .env.prod
    command: celery -A app.worker worker -Q domain_verification_queue --loglevel=info --concurrency=2
    depends_on:
      - redis

  celery_scan_worker:
    build: .
    env_file: .env.prod
    command: celery -A app.worker worker -Q scan_queue --loglevel=info --concurrency=3
    depends_on:
      - redis

  celery_beat:
    build: .
    env_file: .env.prod
    command: celery -A app.worker beat --loglevel=info
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
