"""remove the unique constraint from the domain column

Revision ID: 0ce8051e6c15
Revises: b4563434b572
Create Date: 2025-10-19 10:14:23.393544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0ce8051e6c15'
down_revision: Union[str, Sequence[str], None] = 'b4563434b572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sites_domain'), table_name='sites')
    op.create_index(op.f('ix_sites_domain'), 'sites', ['domain'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sites_domain'), table_name='sites')
    op.create_index(op.f('ix_sites_domain'), 'sites', ['domain'], unique=True)
    # ### end Alembic commands ###
