"""add verification_token_expires_at to the site column

Revision ID: b4563434b572
Revises: b1c158fa34e3
Create Date: 2025-10-18 22:07:42.306364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b4563434b572'
down_revision: Union[str, Sequence[str], None] = 'b1c158fa34e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('verification_token_expires_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'verification_token_expires_at')
    # ### end Alembic commands ###
